---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alexwijn/docker-git-php-composer

inputs:
  - name: source-code

outputs:
  - name: build-artifact

run:
  path: ci/scripts/build.sh
  dir: source-code

