---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alexwijn/docker-git-php-composer

inputs:
  - name: build-artifact

outputs:
  - name: releases

run:
  path: ci/scripts/create-tar.sh
  dir: build-artifact

