---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alexwijn/docker-git-php-composer

inputs:
  - name: release
  - name: source-code

run:
  path: source-code/ci/scripts/deploy-release.sh

