---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alexwijn/docker-git-php-composer

inputs:
  - name: source-code

outputs:
  - name: source-code-with-dependencies

run:
  path: ci/scripts/install-dependencies.sh
  dir: source-code

