---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alexwijn/docker-git-php-composer

inputs:
- name: build-artifact

run:
  path: ci/scripts/run-php-linter.sh
  dir: build-artifact
