---

resources:

- name: source-code
  type: git
  source:
    uri: git@github.com:pavlepredic/concourse-demo.git
    branch: master
    private_key: {{github_private_key}}

- name: release
  type: github-release
  source:
    owner: pavlepredic
    repository: concourse-demo
    access_token: {{github_access_token}}

jobs:

- name: Run linter
  serial: true
  plan:

  - get: source-code
    trigger: true

  - task: run-php-linter
    file: source-code/ci/tasks/run-php-linter.yml

- name: Run tests
  serial: true
  plan:

  - get: source-code
    trigger: true

  - task: build
    file: source-code/ci/tasks/build.yml

  - task: run-tests
    file: build-artifact/ci/tasks/run-tests.yml

- name: Create release
  serial: true
  plan:

  - get: source-code
    trigger: true
    passed:
      - Run linter
      - Run tests

  - task: build
    file: source-code/ci/tasks/build.yml

  - task: create-tar
    file: build-artifact/ci/tasks/create-tar.yml 

  - put: release
    params:
      name: build-artifact/version
      tag: build-artifact/version
      globs:
      - releases/*.tar.gz

- name: Deploy to production
  serial: true
  plan:

  - get: release
    passed:
      - Create release

  - get: source-code

  - task: deploy
    file: source-code/ci/tasks/deploy-release.yml
    params:
      AWS_PRIVATE_KEY: {{aws_private_key}}
      AWS_USERNAME: {{aws_username}}
      AWS_IP: {{aws_production_ip}}
      APP_ENV: production

- name: Deploy to staging
  serial: true
  plan:

  - get: release
    passed:
      - Create release

  - get: source-code

  - task: deploy
    file: source-code/ci/tasks/deploy-release.yml
    params:
      AWS_PRIVATE_KEY: {{aws_private_key}}
      AWS_USERNAME: {{aws_username}}
      AWS_IP: {{aws_staging_ip}}
      APP_ENV: staging