---

resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    
resources:

- name: source-code
  type: pull-request
  source:
    repo: pavlepredic/concourse-demo
    access_token: {{github_access_token}}
    
jobs:

# Run Tests & linter
#-----------------------------------------------------------------------------------------------------------------------
- name: test
  serial: true
  plan:

  # Trigger tests when a PR is merged
  - get: source-code
    trigger: true

  # Set the tests github status for this PR to pending
  - put: source-code
    params:
      path: source-code
      context: tests
      status: pending

  # Run linter against changed PHP files
  - task: run-php-linter
    file: source-code/ci/tasks/run-php-linter.yml

    # Build
  - task: build
    file: source-code/ci/tasks/build.yml
      
  # Run tests
  - task: run-tests
    file: build-artifact/ci/tasks/run-tests.yml

  # On success, set the tests github status for this PR to success
  on_success:
    put: source-code
    params:
      path: source-code
      context: tests
      status: success

  # On failure, set the tests github status for this PR to failure
  on_failure:
    put: source-code
    params:
      path: source-code
      context: tests
      status: failure

- name: deploy
  serial: true
  plan:

  - get: source-code

   # Build
  - task: build
    file: source-code/ci/tasks/build.yml

   # Deploy
  - task: deploy
    file: build-artifact/ci/tasks/deploy.yml
    params:
      AWS_PRIVATE_KEY: {{aws_private_key}}
      AWS_USERNAME: {{aws_username}}
      AWS_IP: {{aws_ip}}
