---

resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    
resources:

- name: source-code
  type: pull-request
  source:
    repo: pavlepredic/concourse-demo
    access_token: {{github_access_token}}
    
jobs:

- name: Run linter
  serial: true
  plan:

  - get: source-code
    trigger: true

  - put: source-code
    params:
      path: source-code
      context: linter
      status: pending

  - task: run-php-linter
    file: source-code/ci/tasks/run-php-linter.yml

  on_success:
    put: source-code
    params:
      path: source-code
      context: linter
      status: success

  on_failure:
    put: source-code
    params:
      path: source-code
      context: linter
      status: failure


- name: Run tests
  serial: true
  plan:

  - get: source-code
    trigger: true

  - put: source-code
    params:
      path: source-code
      context: tests
      status: pending

  - task: build
    file: source-code/ci/tasks/build.yml

  - task: run-tests
    file: build-artifact/ci/tasks/run-tests.yml

  on_success:
    put: source-code
    params:
      path: source-code
      context: tests
      status: success

  on_failure:
    put: source-code
    params:
      path: source-code
      context: tests
      status: failure


- name: Deploy to staging
  serial: true
  plan:

  - get: source-code
    trigger: true
    passed:
      - Run tests
      - Run linter

  - task: build
    file: source-code/ci/tasks/build.yml

  - task: deploy
    file: build-artifact/ci/tasks/deploy.yml
    params:
      AWS_PRIVATE_KEY: {{aws_private_key}}
      AWS_USERNAME: {{aws_username}}
      AWS_IP: {{aws_staging_ip}}
      APP_ENV: staging
